### ISSUE TITLE
'Sphero' object has no attribute 'disconnect'

### ISSUE THREAD

**Issue by crvogt** [jchadwhite/SpheroBB8-python#1]
I assume this is a pretty easy fix, but my Python skillz are minimal. Is there a particularly reason for this error/has anyone else been experiencing it?

**Comment by adamcubel** [comment]
I saw this when attempting to map the disconnect to a button on the controller. In the driver.py under the Sphero class, the last four function def's are not properly indented for the class. Indent each one time, and you should be able to use everything as desidred.

**Comment by crvogt** [comment]
Ah gotcha. I'll give that a try tonight. Thanks for replying

**Comment by KrustyHack** [comment]
Fixed in https://github.com/jchadwhite/SpheroBB8-python/pull/2. Awaiting merge.

**Comment by jchadwhite** [comment]
Thanks for the fix! It was kinda a quick throw together hack of 2 libraries just to get things up and going.
